// <auto-generated />
namespace VPlayer.AudioStorage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class migration_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_4));
        
        string IMigrationMetadata.Id
        {
            get { return "202008280123375_migration_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
