// <auto-generated />
namespace VPlayer.AudioStorage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class migration_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_));
        
        string IMigrationMetadata.Id
        {
            get { return "202009190746022_migration_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
