using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using VPlayer.AudioStorage;
using VPlayer.AudioStorage.Interfaces;
using VPlayer.Core.DomainClasses;
using VPlayer.Core.ViewModels;
using VPlayer.Core.ViewModels.Artists;
using VPlayer.Library.Properties;
using VPlayer.Library.ViewModels;
using VPlayer.Library.ViewModels.LibraryViewModels.ArtistsViewModels;

namespace VPlayer.Library.VirtualList
{
    public class PlayableItemsGenerator<TViewModel, TModel> : IObjectGenerator<TViewModel> 
        where TViewModel : class, IPlayableViewModel<TModel>
        where TModel : INamedEntity
    {
        private readonly PagedEmployeeRepository<TViewModel,TModel> _repository;
        //public PlayableItemsGenerator()
        //{
        //    using (IStorage storage = StorageManager.GetStorage())
        //    {
        //        var itemsEnumerable = storage.GetItems<TModel>();

        //        if (itemsEnumerable != null)
        //            _repository = new PagedEmployeeRepository<TModel>(itemsEnumerable.ToArray());
        //    }
        //}

        public PlayableItemsGenerator(IEnumerable<TViewModel> source)
        {
            _repository = new PagedEmployeeRepository<TViewModel,TModel>(source.ToArray());
        }

        #region IObjectGenerator<SampleObject> Members
        /// <summary>
        /// Number of items that are generated by this object.
        /// </summary>
        public int Count
        {
            get
            {
                // Return the number of objects in the array
                return _repository.Count();
            }
        }

        /// <summary>
        /// Create the object at the specified index.
        /// </summary>
        /// <param name="index">Object index.</param>
        /// <returns>New object instance.</returns>
        public TViewModel CreateObject(int index)
        {
            return _repository.GetAt(index);
        }
        #endregion
    }

    public class PagedEmployeeRepository<TViewModel,TModel> where TViewModel : IPlayableViewModel<TModel>
    where TModel : INamedEntity
    {
        private readonly TViewModel[] source;
        private TViewModel[] _cache;
        public int NumberOfEmployees = -1;

        public PagedEmployeeRepository([NotNull] TViewModel[] source)
        {
            this.source = source ?? throw new ArgumentNullException(nameof(source));
            NumberOfEmployees = source.Length;
        }

        public int PageCursor { get; set; }

        private int _pageSize = 40;

        public int PageSize
        {
            get { return _pageSize; }
            set { _pageSize = value; }
        }

        private int PageCursorStartIndex
        {
            get { return PageCursor * PageSize; }
        }

        public void Clear()
        {
            _cache = null;
        }

        public int Count()
        {
            var employees = DoLoadPage();
            _cache = new TViewModel[NumberOfEmployees];
            UpdateCache(employees);
            return NumberOfEmployees;
        }

        protected List<TViewModel> LoadPage()
        {
            var employees = DoLoadPage();
            UpdateCache(employees);
            return employees;
        }

        protected virtual List<TViewModel> DoLoadPage()
        {
            var employees = new List<TViewModel>();
            for (int i = PageCursorStartIndex; i < PageCursorStartIndex + PageSize; i++)
            {
                if (source.Length > i)
                {
                    Thread.Sleep(TimeSpan.FromMilliseconds(1));
                    employees.Add(source[i]);
                }
            }
            return employees;
        }

        private void UpdateCache(List<TViewModel> compounds)
        {
            for (int i = PageCursorStartIndex; i < PageCursorStartIndex + compounds.Count; i++)
            {
                if (i < _cache.Length)
                    _cache[i] = compounds[i - PageCursorStartIndex];
            }
        }

        public TViewModel GetAt(int index)
        {
            if (index < NumberOfEmployees && _cache[index] == null)
            {
                PageCursor = index / PageSize;
                LoadPage();
            }
            if (index >= NumberOfEmployees)
                throw new ArgumentException(string.Format("employee index [{0}] is exceed the upper boundary [{1}]", index,
                    NumberOfEmployees));
            return _cache[index];
        }

        public int IndexOf(TViewModel employee)
        {
            var result =
                _cache.Where(each => each != null && each.Name == employee.Name).Select((each, index) => new { Position = index, employee }).
                    FirstOrDefault();
            return result != null ? result.Position : -1;
        }
    }
}
